In [1]:
import numpy as np # matematiksel işlemler için kullanılan kütüphane
import pandas as pd # veri işleme kütüphanesi

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
        print(os.path.join(dirname))


In [2]:
import warnings
warnings.filterwarnings('ignore') 

In [3]:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Convolution2D,MaxPooling2D,Flatten 
import tensorflow as tf
import matplotlib.pyplot as plt
from IPython.display import HTML
import os

In [5]:
os.environ['KMP_DUPLICATE_LIB_OK']='True'  #kernel died şeklinde alınan hataya karşılık eklendi
print(tf.__version__) 

2.10.0


In [6]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
IMAGE_SIZE = 128

# Eğitim veri seti için ImageDataGenerator objesi oluşturur. 
#Bu, görüntülerde çeşitli rastgele dönüşümler (döndürme, ölçeklendirme, kaydırma vb.) uygular. 
# Bu teknik, modelin genelleme yeteneğini artırmak için kullanılır.
train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=20,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
)
# Test veri seti için ImageDataGenerator objesi oluşturur. 
test_datagen = ImageDataGenerator(rescale=1./255)

# Eğitim veri setini okur, ölçeklendirir.
train_generator = train_datagen.flow_from_directory(
        'dataset/Cars_Dataset/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        class_mode="sparse",
)  
# Test veri setini okur, ölçeklendirir.
test_generator = test_datagen.flow_from_directory(
        'dataset/Cars_Dataset/test',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        class_mode="sparse",
)


Found 4514 images belonging to 7 classes.
Found 813 images belonging to 7 classes.


In [7]:
count=0
for image_batch, label_batch in train_generator:
    print(label_batch)
    print(image_batch[0])
    break  

[5. 3. 6. 4. 3. 2. 0. 3. 6. 2. 0. 1. 5. 4. 6. 0. 6. 0. 2. 4. 4. 5. 3. 6.
 2. 6. 3. 6. 2. 5. 4. 0.]
[[[1.89044461e-01 2.12573871e-01 2.72877485e-01]
  [2.17957750e-01 2.41487160e-01 3.03005397e-01]
  [2.48691663e-01 2.72221088e-01 3.34953904e-01]
  ...
  [3.52517888e-02 5.88376448e-02 2.86302745e-01]
  [6.65611252e-02 1.05724044e-01 5.80253825e-02]
  [5.80882058e-02 8.94957483e-02 9.38377231e-02]]

 [[1.76710084e-01 1.95944324e-01 2.52278000e-01]
  [2.07714394e-01 2.28770524e-01 2.84496903e-01]
  [2.36092836e-01 2.58970857e-01 3.14089954e-01]
  ...
  [4.30947468e-02 7.05244765e-02 2.29329944e-01]
  [7.45028630e-02 1.17636643e-01 5.07159239e-05]
  [5.25289886e-02 7.99656659e-02 1.25604659e-01]]

 [[2.05499142e-01 2.18906567e-01 2.72801965e-01]
  [2.18385711e-01 2.31185839e-01 2.86903113e-01]
  [2.43223354e-01 2.55416155e-01 3.12955350e-01]
  ...
  [5.10364808e-02 8.24370757e-02 1.71355277e-01]
  [6.89554587e-02 1.08125322e-01 3.17391492e-02]
  [4.70588282e-02 7.05882385e-02 1.56862751e-0

In [8]:
classes = list(train_generator.class_indices.keys())
classes

['Audi',
 'Hyundai Creta',
 'Mahindra Scorpio',
 'Rolls Royce',
 'Swift',
 'Tata Safari',
 'Toyota Innova']

In [9]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break  #test veri üreteci için asıl çalıştığını ve ürettiği verinin nasıl göründüğünü gösterir.

[[[0.01176471 0.05882353 0.01960784]
  [0.         0.04313726 0.00392157]
  [0.         0.01568628 0.        ]
  ...
  [0.5882353  0.67058825 0.5411765 ]
  [0.2901961  0.37254903 0.24313727]
  [0.3803922  0.46274513 0.30980393]]

 [[0.         0.02745098 0.        ]
  [0.00392157 0.0509804  0.01176471]
  [0.03529412 0.07450981 0.03921569]
  ...
  [0.21960786 0.3019608  0.17254902]
  [0.33333334 0.41960788 0.2784314 ]
  [0.21568629 0.29803923 0.12941177]]

 [[0.         0.03529412 0.        ]
  [0.02352941 0.0627451  0.02745098]
  [0.0509804  0.09019608 0.05490196]
  ...
  [0.18039216 0.26666668 0.1254902 ]
  [0.19607845 0.28235295 0.14117648]
  [0.25882354 0.34509805 0.16078432]]

 ...

 [[0.45098042 0.45098042 0.4901961 ]
  [0.454902   0.454902   0.49411768]
  [0.45882356 0.45882356 0.49803925]
  ...
  [0.34509805 0.37254903 0.41176474]
  [0.34117648 0.36862746 0.40784317]
  [0.33333334 0.36862746 0.4039216 ]]

 [[0.44705886 0.44705886 0.48627454]
  [0.45098042 0.45098042 0.4901961 ]


In [10]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

sz = 128

# CNN başlatılır
model = Sequential()

# İlk evrişim katmanı ve havuzlama 
model.add(Conv2D(64, (3, 3), input_shape=(sz, sz, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# İkinci evrişim katmanı ve havuzlama
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Üçüncü evrişim katmanı
model.add(Conv2D(128, (3, 3), activation='relu'))

# Katmanları düzleştirme
model.add(Flatten())

# Tamamen bağlı bir katman ekleme
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=7, activation='softmax'))   #birimler, sınıf sayısıyla eşleşmesini doğrular


In [11]:
model.summary() 

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 64)      1792      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 28, 28, 128)       73856     
                                                                 
 flatten (Flatten)           (None, 100352)            0

In [ ]:

from tensorflow import keras
from tensorflow.keras.optimizers import Adam

# Öğrenme oranını belirler. Bu değer, her iterasyonda modelin ağırlıklarının ne kadar hızlı güncelleneceğini kontrol eder.
learning_rate = 0.001  

# Adam optimizer'ını belirlenen öğrenme oranıyla başlatır.
optimizer = Adam(learning_rate=learning_rate)

# Model derlenir. 
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

#Model eğitilir.
history = model.fit(
    train_generator,
    validation_data=test_generator,
    epochs=40
)


Epoch 1/40
142/142 [==============================] - 105s 727ms/step - loss: 1.9324 - accuracy: 0.2062 - val_loss: 1.8133 - val_accuracy: 0.2460
Epoch 2/40
142/142 [==============================] - 92s 649ms/step - loss: 1.8138 - accuracy: 0.2809 - val_loss: 1.7445 - val_accuracy: 0.3419
Epoch 3/40
142/142 [==============================] - 94s 660ms/step - loss: 1.7729 - accuracy: 0.2935 - val_loss: 1.6595 - val_accuracy: 0.3493
Epoch 4/40
142/142 [==============================] - 92s 644ms/step - loss: 1.7250 - accuracy: 0.3257 - val_loss: 1.6745 - val_accuracy: 0.4034
Epoch 5/40
142/142 [==============================] - 94s 659ms/step - loss: 1.6827 - accuracy: 0.3445 - val_loss: 1.6398 - val_accuracy: 0.4194
Epoch 6/40
142/142 [==============================] - 91s 643ms/step - loss: 1.6628 - accuracy: 0.3624 - val_loss: 1.5721 - val_accuracy: 0.4170
Epoch 7/40
142/142 [==============================] - 93s 653ms/step - loss: 1.6404 - accuracy: 0.3704 - val_loss: 1.5432 - val_a

In [ ]:
#test veri seti üzerinde modelin performansını değerlendirir.
scores = model.evaluate(test_generator)

In [ ]:
scores

In [ ]:
history.history.keys()

In [ ]:
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

In [ ]:
import matplotlib.pyplot as plt
EPOCHS = 40

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(range(EPOCHS), acc, label='Training Accuracy')
plt.plot(range(EPOCHS), val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(range(EPOCHS), loss, label='Training Loss')
plt.plot(range(EPOCHS), val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

In [ ]:
import numpy as np
import tensorflow as tf
from keras.preprocessing import image
def predict(model, img_path, classes):
    # Görüntüyü yükler, modelin beklediği şekle getirir ve piksel değerlerini normalize eder
    img_array = tf.keras.preprocessing.image.img_to_array(images[i])
    
    img_array = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_array)

    predicted_class = classes[np.argmax(predictions[0])]
    confidence = round(100 * (np.max(predictions[0])), 2)
    return predicted_class, confidence


In [ ]:
plt.figure(figsize=(15, 15))

In [ ]:
for images, labels in test_generator:
    for i in range(6):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i])
        
        predicted_class, confidence = predict(model, images[i], classes)
        actual_class = classes[int(labels[i])] 
        
        plt.title(f"Actual: {actual_class},\n Predicted: {predicted_class}.\n Confidence: {confidence}%")
        
        plt.axis("off")
    break

In [ ]:
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Sabit değişkenler tanımlandı
IMAGE_SIZE = [224,224]
TRAIN_DIR = 'dataset/Cars_Dataset/train/*'

# Üst katmanları dışlayacak şekilde yapılandırılmış, önceden eğitilmiş VGG16 modeli yüklenir
base_model = VGG16(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

# VGG16'nın katmanlarını dondurulur
for layer in base_model.layers:
    layer.trainable = False

# Sınıf sayısını alınır
folders = glob(TRAIN_DIR)
num_classes = len(folders)

# Yeni katmanlar eklenir
x = Flatten()(base_model.output)
output = Dense(num_classes, activation='softmax')(x)

# Model tanımlanır
model = Model(inputs=base_model.input, outputs=output)

# Model derlenir
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

# Modelin yapısı gösterilir
model.summary()

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator 

# Eğitim için veri artırmalı ve eğitim/test için veri artırmasız veri oluşturucuları tanımlanır
train_datagen = ImageDataGenerator(rescale=1./255, shear_range = 0.2, zoom_range=0.2, horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)

# Dizinler tanımlanır
TRAIN_DIR = 'dataset/Cars_Dataset/train/'
TEST_DIR = 'dataset/Cars_Dataset/test/'

# Görüntü özelliklerini tanımlanır
TARGET_SIZE = (224,224)
BATCH_SIZE = 32
CLASS_MODE = 'categorical'

# Eğitim verileri yüklenir
training_set = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=TARGET_SIZE,
    batch_size=BATCH_SIZE,
    class_mode=CLASS_MODE)

# Test verileri yüklenir
test_set = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=TARGET_SIZE,
    batch_size=BATCH_SIZE,
    class_mode=CLASS_MODE)

# Model fit parametreleri tanımlanır
EPOCHS = 10
STEPS_PER_EPOCH = len(training_set)
VALIDATION_STEPS = len(test_set)

# Model iyileştirilir
history = model.fit(
    training_set, 
    validation_data=test_set,
    epochs=EPOCHS,
    steps_per_epoch=STEPS_PER_EPOCH,
    validation_steps=VALIDATION_STEPS)


In [ ]:
from sklearn.metrics import classification_report
import numpy as np

# Etiketler ve tahminler için boş listeler oluşturulur
y_true = []
y_pred = []

# Test veri setinin her bir batch'i için tahminleri alınır
for i in range(len(test_set)):
    images, labels = next(test_set)
    pred_probs = model.predict(images)
    preds = np.argmax(pred_probs, axis=1)
    true_labels = np.argmax(labels, axis=1)

    y_true.extend(true_labels)
    y_pred.extend(preds)

# Sınıflandırma raporunu hesaplar ve yazdırır
class_labels = list(test_set.class_indices.keys())
report = classification_report(y_true, y_pred, target_names=class_labels)
print(report)
